/*
 O prensente projeto tem o intuito de resolver o exec 23 do capitulo 3 de Sistema Operacional
 */
package sistopercap3exerc23;


import java.util.ArrayList;
import java.util.List;


/**
 *
 * @author Donato
 */
public class SistemaOperacional extends javax.swing.JFrame {
List<Pagina> lista = new ArrayList<Pagina>();//variavél global que armazenará a lista de páginas
String resultListaPagina="";//resultado da lista que será impresso
String resultListaPaginaRemovidas="";//resultado da lista das páginas removidas
int tamanho;
    public SistemaOperacional() {
        initComponents();
       
    
    }
    
    public void AddLista(){   //Adiciona na lista todos os dados inseridos pelo usuário
        
     lista.add(new Pagina("A",Integer.valueOf(jComboBoxA.getSelectedItem().toString())));//Cria uma página e adiciona na lista principal, os dados fornecidos no comboBox.
     lista.add(new Pagina("B",Integer.valueOf(jComboBoxB.getSelectedItem().toString())));
     lista.add(new Pagina("C",Integer.valueOf(jComboBoxC.getSelectedItem().toString())));  
     lista.add(new Pagina("D",Integer.valueOf(jComboBoxD.getSelectedItem().toString())));
     lista.add(new Pagina("E",Integer.valueOf(jComboBoxE.getSelectedItem().toString())));
     lista.add(new Pagina("F",Integer.valueOf(jComboBoxF.getSelectedItem().toString()))); 
     lista.add(new Pagina("G",Integer.valueOf(jComboBoxG.getSelectedItem().toString())));
     lista.add(new Pagina("H",Integer.valueOf(jComboBoxH.getSelectedItem().toString()))); 
     tamanho = lista.size();//ARMAZENA O TAMANHO INICIAL DA LISTA
     PreencheListaDados();//chama o procedimento que irá preencher a string resultListaPagina os valores fornecidos pelo usuário
    }
    
    public void VerificaBits (){//Procedimento que irá verificar quais os bits de cada página
       
        for(int i=0; i<=lista.size();i++){  //laço que irá percorrer a lista até chegar ao seu tamanho 
            if(lista.get(i).getBist()==0){ //verifica se a pagina com o indice "i" possui bits 0
                resultListaPaginaRemovidas= resultListaPaginaRemovidas+(lista.get(i).getNome());// Armazena na váriavel o nome da pág que tem índice 0
                lista.remove(lista.get(i));//Remove a pág com bits 0 da lista principal
                break;// sai do laço, pois a intenção é mostrar a remoção das páginas passo a passo
            }else{
                lista.get(i).setBist(0);//Caso a página tenha bit = 1 é alterado o bit para 0
                lista.add(lista.get(i));//adiciona a página no final da lista
                lista.remove(lista.get(i));//remove a página do inicio da lista
                break;// sai do laço, pois a intenção é mostrar a remoção das páginas passo a passo
            }
        }
        
    }
    
    public void ImprimeDadosRemovidos(String removidos){//imprime na JTexArea a lista das páginas removidas
        jTextAreaRemovidos.setText(removidos);
    }
    
     public void ImprimeListaDados(String lista){ //imprime na JTexArea a lista principal das páginas
        jTextAreaResult1.setText(lista);
    }
    
     public void PreencheListaDados(){//Armazena na variavel resulListaPagina o nome das páginas e seus respectivos bits de referência
         
        for (Pagina p : lista){//Laço que passa por cada página presente na variavel global lista
            resultListaPagina= resultListaPagina +" "+p.getNome()+"--> "+ p.getBist()+", ";
        } 
        resultListaPagina=resultListaPagina+"\n";
    }
     
    public void DesabilitaBtm(){
        jComboBoxH.setEnabled(false);
        jComboBoxA.setEnabled(false);
        jComboBoxB.setEnabled(false);
        jComboBoxC.setEnabled(false);
        jComboBoxD.setEnabled(false);
        jComboBoxE.setEnabled(false);
        jComboBoxF.setEnabled(false);
        jComboBoxG.setEnabled(false);
        jButton1.setEnabled(false);
        lista.clear();
        resultListaPagina="";
        resultListaPaginaRemovidas="";
    }
    
    public void HabilitaBtm(){
         jComboBoxH.setEnabled(true);
        jComboBoxA.setEnabled(true);
        jComboBoxB.setEnabled(true);
        jComboBoxC.setEnabled(true);
        jComboBoxD.setEnabled(true);
        jComboBoxE.setEnabled(true);
        jComboBoxF.setEnabled(true);
        jComboBoxG.setEnabled(true);
        jButton1.setEnabled(true);
        jTextAreaResult1.setText("");
        jTextAreaRemovidos.setText("");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBoxB = new javax.swing.JComboBox<>();
        jComboBoxC = new javax.swing.JComboBox<>();
        jComboBoxE = new javax.swing.JComboBox<>();
        jComboBoxD = new javax.swing.JComboBox<>();
        jComboBoxF = new javax.swing.JComboBox<>();
        jComboBoxG = new javax.swing.JComboBox<>();
        jComboBoxH = new javax.swing.JComboBox<>();
        jComboBoxA = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaRemovidos = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaResult1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2474444, 24744444));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Observe a sequência das Páginas da figura 3.14(b). Suponha que os bits R, para as páginas de B a A, sejam 11011011, respectivamente. Quais páginas serão removidas pelo algoritmo segunda chance?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1152, 39));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("EXECUTAR");
        jButton1.setToolTipText("Clique para responder a perguntar do exercício");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(255, 255, 255), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(934, 125, -1, 44));

        jComboBoxB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));
        jComboBoxB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxB, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 159, -1, -1));

        jComboBoxC.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));
        jComboBoxC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jComboBoxC, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 159, -1, -1));

        jComboBoxE.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));
        jComboBoxE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jComboBoxE, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 159, -1, -1));

        jComboBoxD.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));
        jComboBoxD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jComboBoxD, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 159, -1, -1));

        jComboBoxF.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));
        jComboBoxF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jComboBoxF, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 159, -1, -1));

        jComboBoxG.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));
        jComboBoxG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jComboBoxG, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 159, -1, -1));

        jComboBoxH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));
        jComboBoxH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jComboBoxH, new org.netbeans.lib.awtextra.AbsoluteConstraints(822, 159, -1, -1));

        jComboBoxA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));
        jComboBoxA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jComboBoxA, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 159, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel3.setText("H");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, -1, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel4.setText("F");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 85, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel5.setText("E");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 85, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel6.setText("D");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 85, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel7.setText("C");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 85, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel8.setText("B");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 85, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel9.setText("A");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 85, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel10.setText("G");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 85, -1, -1));

        jTextAreaRemovidos.setColumns(20);
        jTextAreaRemovidos.setRows(5);
        jTextAreaRemovidos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextAreaRemovidos.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreaRemovidos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 239, -1, 343));

        jTextAreaResult1.setColumns(20);
        jTextAreaResult1.setRows(5);
        jTextAreaResult1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextAreaResult1.setEnabled(false);
        jScrollPane2.setViewportView(jTextAreaResult1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 239, 401, 343));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SEQUÊNCIA DAS PÁGINAS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("PÁGINA REMOVIDA");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 150, -1));

        jLabel12.setText("Páginas --->");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 104, -1, -1));

        jLabel13.setText("Bits ------->");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 164, -1, -1));

        jButton2.setText("RESETAR");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 560, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AddLista();//Chama o procedimento addLista que irá adicionar a lista todas a páginas e seus respectivos bits preenchidos pelo usuário
        
        while (lista.size()==tamanho){//laço que irá ser executado enquanto a lista tiver o mesmo tamanho quando iniciou
            VerificaBits();//chama o procedimento que irá verificar qual bits cada página possui
            PreencheListaDados();//chama o procedimento que irá armazenar a próxima linha com as páginas que não foram removidas
            resultListaPaginaRemovidas=resultListaPaginaRemovidas+"\n";//faz a variavel que esta armazenando as páginas removidas pular uma linha
        }
         ImprimeDadosRemovidos(resultListaPaginaRemovidas);//chama o procedimento que irá imprimir na tela a lista das páginas removidas
         ImprimeListaDados(resultListaPagina);//chama o procedimento que irá imprimir na tela a lista principal das páginas
         DesabilitaBtm();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        HabilitaBtm();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaOperacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaOperacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaOperacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaOperacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaOperacional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxA;
    private javax.swing.JComboBox<String> jComboBoxB;
    private javax.swing.JComboBox<String> jComboBoxC;
    private javax.swing.JComboBox<String> jComboBoxD;
    private javax.swing.JComboBox<String> jComboBoxE;
    private javax.swing.JComboBox<String> jComboBoxF;
    private javax.swing.JComboBox<String> jComboBoxG;
    private javax.swing.JComboBox<String> jComboBoxH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaRemovidos;
    private javax.swing.JTextArea jTextAreaResult1;
    // End of variables declaration//GEN-END:variables
}
